### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by priyapurushothaman** [priyapurushothaman/Testing#7]
> Test chat from Priya

**Link:** [Conversation with Priya](https://app.intercom.com/a/apps/xhnn6n6y/respond/inbox/all/conversations/12995264575)

**Customer:** [Priya](https://app.intercom.com/a/apps/xhnn6n6y/users/5a047f6082e2a7c935202067/all-conversations) from [Counseling Las Cruces](https://app.intercom.com/a/apps/xhnn6n6y/companies/5668ae8d4649513b36000583)
**Customer ID:** r005e1510244171652
**Company ID:** 7d922400-a801-4a7a-84dc-acdee0ce98fc
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xhnn6n6y/respond/inbox/all/conversations/12995264575) when this issue is closed.

**Comment by priyapurushothaman** [comment]
Udhaya is this for Office or Google.

**Comment by priyapurushothaman** [comment]
Is this for One way sync or two way sync?

**Comment by udhaya21** [comment]
Google 2-way sync

**Comment by udhaya21** [comment]
Is this issue fixed?

**Comment by priyapurushothaman** [comment]
Issue is fixed please reply back to the customer

**Comment by priyapurushothaman** [comment]
https://app.intercom.com/a/apps/xhnn6n6y/respond/inbox/unassigned/conversations/12995343676

**Comment by priyapurushothaman** [comment]
https://app.intercom.com/a/apps/xhnn6n6y/respond/inbox/unassigned/conversations/12995350802
